# Generated by Django 6.0.1 on 2026-03-16 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL (slug)")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CLUB", "Кружок"),
                            ("PROGRAM", "Продленка/Программа"),
                            ("SERVICE", "Услуга"),
                        ],
                        default="CLUB",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activities/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Сортировка"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен на сайте"),
                ),
            ],
            options={
                "verbose_name": "Направление (Кружок/Услуга)",
                "verbose_name_plural": "Направления (Кружки и Услуги)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="ФИО родителя"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, verbose_name="Комментарии / Вопросы с сайта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Родитель (Клиент)",
                "verbose_name_plural": "Родители (Клиенты)",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="ФИО ребенка"),
                ),
                (
                    "school_grade",
                    models.CharField(blank=True, max_length=20, verbose_name="Класс"),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Дата рождения",
                    ),
                ),
                (
                    "health_issues",
                    models.TextField(blank=True, verbose_name="Особенности здоровья"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="services.parent",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ученик",
                "verbose_name_plural": "Ученики",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название тарифа"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Цена"
                    ),
                ),
                (
                    "sessions_count",
                    models.PositiveIntegerField(verbose_name="Количество занятий"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.activity",
                        verbose_name="Привязка к кружку",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф (Шаблон)",
                "verbose_name_plural": "Тарифы (Шаблоны)",
                "ordering": ["activity", "price"],
            },
        ),
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="teachers/",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="О себе / Биография"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Порядок отображения"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь (Логин/Пароль)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль учителя",
                "verbose_name_plural": "Команда (Учителя)",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Сумма"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Ожидает оплаты"),
                            ("CONFIRMED", "Оплачен (Подтвержден)"),
                            ("REJECTED", "Отклонен / Ошибка"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.parent",
                        verbose_name="Родитель (Плательщик)",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.subscriptionplan",
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на оплату (Транзакция)",
                "verbose_name_plural": "Заявки на оплату (Транзакции)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeeklySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Начало")),
                ("end_time", models.TimeField(verbose_name="Конец")),
                (
                    "group_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Название группы"
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(default=10, verbose_name="Вместимость"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="services.activity",
                        verbose_name="Направление",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.teacherprofile",
                        verbose_name="Учитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот расписания",
                "verbose_name_plural": "Расписание",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(db_index=True, verbose_name="Дата исключения"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CANCELLATION", "Отмена"), ("RESCHEDULE", "Перенос")],
                        max_length=20,
                        verbose_name="Тип изменения",
                    ),
                ),
                (
                    "new_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Новое время (если перенос)"
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="services.weeklyslot",
                        verbose_name="Слот расписания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исключение из расписания (Отмена/Перенос)",
                "verbose_name_plural": "Исключения из расписания",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "remaining_sessions",
                    models.PositiveIntegerField(verbose_name="Осталось занятий"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="services.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="services.subscriptionplan",
                        verbose_name="Тариф",
                    ),
                ),
            ],
            options={
                "verbose_name": "Абонемент ученика",
                "verbose_name_plural": "Абонементы учеников",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("remaining_sessions__gte", 0)),
                        name="positive_remaining_sessions",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_enrolled",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Дата записи"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="services.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="services.weeklyslot",
                        verbose_name="Слот расписания",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись в группу",
                "verbose_name_plural": "Записи в группы",
                "unique_together": {("student", "slot")},
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Дата занятия",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Был (Списание)"),
                            ("ABSENT", "Не был (Списание)"),
                            ("EXCUSED", "Болел (Без списания)"),
                        ],
                        default="PRESENT",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="services.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="services.weeklyslot",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отметка посещаемости",
                "verbose_name_plural": "Журнал (Посещаемости)",
                "unique_together": {("student", "slot", "date")},
            },
        ),
    ]
