# Generated by Django 6.0.1 on 2026-03-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название события')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время начала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена билета')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Обложка (Афиша)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Событие (Афиша)',
                'verbose_name_plural': 'Афиша (События)',
                'ordering': ['-date_time'],
            },
        ),
    ]
