# Generated by Django 6.0.1 on 2026-03-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий (и откуда узнали)"
            ),
        ),
    ]
