# Generated by Django 6.0.1 on 2026-04-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_transaction_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Отметка посещаемости', 'verbose_name_plural': 'Журнал'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Родитель', 'verbose_name_plural': 'Родители'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['activity', 'price'], 'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='teacherprofile',
            options={'ordering': ['display_order'], 'verbose_name': 'Профиль учителя', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на оплату', 'verbose_name_plural': 'Заявки на оплату'},
        ),
        migrations.AddField(
            model_name='activity',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Вывести на главную страницу'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('CLUB', 'Кружок'), ('SERVICE', 'Услуга')], default='CLUB', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='events/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.parent', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='weeklyslot',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Колличество мест'),
        ),
    ]
