# Generated by Django 6.0.1 on 2026-04-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_attendance_options_alter_parent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фотография')),
                ('alt', models.CharField(blank=True, help_text='Текст для слепых и SEO', max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена абонемента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена билета'),
        ),
    ]
